# Generated by Django 5.0 on 2026-04-08 18:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('status_change', 'Status Change'), ('staff_assign', 'Staff Assignment'), ('escalation', 'Auto-Escalation'), ('broadcast', 'System Broadcast'), ('resolve', 'Resolved')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='escalated',
            field=models.BooleanField(default=False, help_text='Whether this alert has been auto-escalated'),
        ),
        migrations.AddField(
            model_name='alert',
            name='group_id',
            field=models.CharField(blank=True, default='', help_text='Group ID for related incidents', max_length=50),
        ),
        migrations.AddField(
            model_name='alert',
            name='priority_score',
            field=models.IntegerField(default=0, help_text='AI-computed priority score'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='idx_alert_status'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='idx_alert_severity'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['timestamp'], name='idx_alert_timestamp'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['emergency_type'], name='idx_alert_type'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'severity'], name='idx_alert_status_sev'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['alert', 'timestamp'], name='idx_chat_alert_ts'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['alert', 'timestamp'], name='idx_audit_alert_ts'),
        ),
    ]
