# Generated by Django 4.2.29 on 2026-04-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auditlog_alert_escalated_alert_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='model_confidence',
            field=models.FloatField(default=0.0, help_text='ML model prediction confidence (0.0-1.0)'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='emergency_type',
            field=models.CharField(choices=[('fire', 'Fire'), ('flood', 'Flood'), ('medical', 'Medical Emergency'), ('routine', 'Routine'), ('security', 'Security Threat')], default='routine', max_length=30),
        ),
    ]
