# Generated by Django 4.2.29 on 2026-04-28 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0003_alert_model_confidence_alter_alert_emergency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='reported_by',
            field=models.ForeignKey(blank=True, help_text='The user who created this alert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
